[options]
addons_path = ./addons,./odoo/addons,./dev/addons
data_dir = ./data
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 123456
admin_passwd = myodoo123
# db_name = odoo
http_port = 8069
log_level = debug
dev = all
proxy_mode = False
xmlrpc_interface = 0.0.0.0
netrpc_interface = 0.0.0.0
longpolling_port = 8072

